defaults:
  - hydra: default
  - _self_

tasks:
  - SUN397
  - Cars
  - RESISC45
  - EuroSAT
  - SVHN
  - GTSRB
  - MNIST
  - DTD

# model arguments
model: ViT-B-32
save: ??? # save location of classification heads

# data arguments
data_location: ??? # location of datasets
batch_size: 64
num_workers: 16
